# Generated by Django 3.2.7 on 2022-03-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20220322_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors_speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(blank=True, max_length=30, null=True)),
                ('doctor_user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='my_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Doctors_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('doctor_user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='my_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='A_doctor_specialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_user_id', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('specialities', models.ManyToManyField(blank=True, related_name='doctor_all_specialities', to='my_app.Doctors_speciality')),
            ],
        ),
        migrations.CreateModel(
            name='A_doctor_locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_user_id', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('locations', models.ManyToManyField(blank=True, related_name='doctor_all_locations', to='my_app.Doctors_location')),
            ],
        ),
    ]
