# Generated by Django 3.2.7 on 2022-03-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_a_doctor_locations_a_doctor_specialities_doctors_location_doctors_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors_location',
            name='doctor_user_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='doctors_speciality',
            name='doctor_user_id',
            field=models.CharField(max_length=30),
        ),
    ]
