# Generated by Django 3.2.7 on 2022-03-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20220322_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a_doctor_specialities',
            name='specialities',
        ),
        migrations.DeleteModel(
            name='A_doctor_locations',
        ),
        migrations.DeleteModel(
            name='A_doctor_specialities',
        ),
    ]
