# Generated by Django 3.2.7 on 2022-03-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_doctors_location_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors_location',
            name='doc_user_id',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctors_location',
            name='doctor_user_id',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
