# Generated by Django 3.2.7 on 2022-03-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20220322_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_locations',
            fields=[
                ('location_id', models.CharField(default='', max_length=4294967295, primary_key=True, serialize=False)),
                ('doctor_user_id', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('doc_user_id', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('clinic_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('building_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('area', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('latitude', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('longitude', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('pin_code', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Doctors_location',
        ),
    ]
