# Generated by Django 3.2.7 on 2022-03-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_auto_20220322_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctors_location',
        ),
    ]
