# Generated by Django 3.2.7 on 2022-03-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_doctors_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors_location',
            name='doc_user_id',
        ),
        migrations.AlterField(
            model_name='doctors_location',
            name='location_id',
            field=models.CharField(max_length=4294967295, primary_key=True, serialize=False),
        ),
    ]
