# Generated by Django 3.2.7 on 2022-03-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_auto_20220322_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors_location',
            name='country',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
