# Generated by Django 3.2.7 on 2022-03-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_doctors_location_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors_speciality',
            new_name='Doctors_specialitie',
        ),
    ]
