# Generated by Django 3.2.7 on 2022-03-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_remove_doctors_specialitie_doctor_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors_specialitie',
            name='speciality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
