# Generated by Django 3.2.7 on 2022-03-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_alter_doctors_specialitie_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
