# Generated by Django 3.2.7 on 2022-03-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_alter_doctor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='license_expiry_date',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_issue_date',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_issuing_authority',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_no',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
