# Generated by Django 3.2.7 on 2022-03-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_auto_20220325_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_user_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('profile_image', models.ImageField(upload_to='media-files/doctors_profile_images')),
            ],
        ),
    ]
