# Generated by Django 3.2.7 on 2022-03-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_auto_20220329_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doc_loc',
        ),
    ]
