# Generated by Django 3.2.7 on 2022-03-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_delete_doc_loc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('loc_id', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
        ),
    ]
