# Generated by Django 3.2.7 on 2022-03-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0030_doctor_location_consaltancy_doctor_video_consaltancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_location_consaltancy',
            name='location_id',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
