# Generated by Django 3.2.7 on 2022-03-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0032_auto_20220329_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='image',
            field=models.FileField(default='', upload_to='media-files/doctors_profile_images'),
        ),
    ]
