# Generated by Django 3.2.7 on 2022-03-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0033_doctor_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_user_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('image', models.FileField(default='', upload_to='media-files/doctors_signature_images')),
            ],
        ),
    ]
