# Generated by Django 3.2.7 on 2022-04-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0034_doctor_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_location_consaltancie',
            name='currency_type',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
