# Generated by Django 3.2.7 on 2022-04-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0036_doctor_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_license',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('license_no', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('license_issue_date', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('license_issuing_authority', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('license_expiry_date', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='license_expiry_date',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='license_issue_date',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='license_issuing_authority',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='license_no',
        ),
    ]
