# Generated by Django 3.2.7 on 2022-04-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0037_auto_20220402_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_schedule',
            name='time_zone_offset',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
