# Generated by Django 3.2.7 on 2022-04-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0038_doctor_schedule_time_zone_offset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_consaltancies_charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('location_id', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('video_consultancy_fees', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('physical_consultancy_fees', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('currency_type', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor_location_consaltancie',
        ),
        migrations.DeleteModel(
            name='Doctor_profile',
        ),
        migrations.DeleteModel(
            name='Doctor_signature',
        ),
        migrations.DeleteModel(
            name='Doctor_video_consaltancie',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
