# Generated by Django 3.2.7 on 2022-04-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0041_auto_20220413_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
