# Generated by Django 3.2.7 on 2022-04-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0042_alter_customer_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_a_priimary_member',
            new_name='is_a_primary_member',
        ),
    ]
