# Generated by Django 3.2.7 on 2022-04-12 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0043_rename_is_a_priimary_member_customer_is_a_primary_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='familiy_code',
            new_name='family_code',
        ),
    ]
