# Generated by Django 3.2.7 on 2022-04-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0045_auto_20220413_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_a_primary_member',
        ),
    ]
