# Generated by Django 3.2.7 on 2022-04-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0048_auto_20220413_0125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
