# Generated by Django 3.2.7 on 2022-04-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0049_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('family_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('email_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('profile_picture', models.ImageField(default='', upload_to='media-files/patients_profile_images')),
            ],
        ),
    ]
