# Generated by Django 3.2.7 on 2022-04-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0051_medical_condition_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_condition_disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_code', models.CharField(max_length=7)),
                ('disease', models.CharField(max_length=228)),
            ],
        ),
        migrations.DeleteModel(
            name='Medical_condition_master',
        ),
    ]
