# Generated by Django 3.2.7 on 2022-04-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0052_auto_20220413_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_condition_disease',
            name='disease',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medical_condition_disease',
            name='icd_code',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
