# Generated by Django 3.2.7 on 2022-04-12 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0053_auto_20220413_0210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medical_condition_disease',
        ),
    ]
