# Generated by Django 3.2.7 on 2022-04-12 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0055_medical_condition_disease'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medical_condition_disease',
        ),
    ]
