# Generated by Django 3.2.7 on 2022-04-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0056_delete_medical_condition_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_condition_disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('disease', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
