# Generated by Django 3.2.7 on 2022-04-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0058_customer_primary_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
