# Generated by Django 3.2.7 on 2022-04-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0061_patient_medical_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAppInsuranceCompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_company_name', models.CharField(blank=True, default='', max_length=40, null=True)),
            ],
        ),
    ]
