# Generated by Django 3.2.7 on 2022-04-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0062_myappinsurancecompanymaster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAppInsuranceCompanyMaster',
        ),
    ]
